/**
 * Pre-seeded Indian & Global Food Database
 * Extended with full macro and micronutrient profiles.
 */

export interface FoodItem {
  id: string;
  name: string;
  servingSize: string;
  calories: number;
  protein: number; // in grams
  carbs: number;   // in grams
  fat: number;     // in grams
  category: "Breakfast" | "Lunch/Dinner" | "Snacks" | "Dairy" | "Breads" | "Other";
  fiber?: number;      // in grams
  sugar?: number;      // in grams
  sodium?: number;     // in milligrams
  potassium?: number;  // in milligrams
  vitaminA?: number;   // in mcg RAE
  vitaminC?: number;   // in mg
  calcium?: number;    // in mg
  iron?: number;       // in mg
  barcode?: string;    // Barcode for barcode scanner demo
  brand?: string;      // Brand name
}

export const INITIAL_FOODS: FoodItem[] = [
  // Breads / Grains
  {
    id: "f1",
    name: "Whole Wheat Roti (No Butter)",
    servingSize: "1 Roti (35g)",
    calories: 85,
    protein: 3,
    carbs: 18,
    fat: 0.5,
    category: "Breads",
    fiber: 2.2,
    sugar: 0.2,
    sodium: 120,
    potassium: 90,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 15,
    iron: 0.8
  },
  {
    id: "f2",
    name: "Butter Roti",
    servingSize: "1 Roti (40g)",
    calories: 120,
    protein: 3.2,
    carbs: 18,
    fat: 3.5,
    category: "Breads",
    fiber: 2.2,
    sugar: 0.2,
    sodium: 150,
    potassium: 92,
    vitaminA: 25,
    vitaminC: 0,
    calcium: 18,
    iron: 0.8
  },
  {
    id: "f3",
    name: "Plain Paratha",
    servingSize: "1 Paratha (60g)",
    calories: 258,
    protein: 4.5,
    carbs: 32,
    fat: 12,
    category: "Breads",
    fiber: 3.5,
    sugar: 0.4,
    sodium: 280,
    potassium: 110,
    vitaminA: 40,
    vitaminC: 0,
    calcium: 22,
    iron: 1.2
  },
  {
    id: "f4",
    name: "Aloo Paratha",
    servingSize: "1 Paratha (90g)",
    calories: 290,
    protein: 5.2,
    carbs: 42,
    fat: 11,
    category: "Breads",
    fiber: 4.2,
    sugar: 0.8,
    sodium: 380,
    potassium: 240,
    vitaminA: 45,
    vitaminC: 4.5,
    calcium: 30,
    iron: 1.5
  },
  {
    id: "f5",
    name: "Basmati Rice (Cooked)",
    servingSize: "1 Katori (150g)",
    calories: 195,
    protein: 4.3,
    carbs: 44,
    fat: 0.4,
    category: "Lunch/Dinner",
    fiber: 1.1,
    sugar: 0.1,
    sodium: 5,
    potassium: 45,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 10,
    iron: 0.6
  },

  // Vegetarian Curries & Dals
  {
    id: "f7",
    name: "Paneer Tikka Masala",
    servingSize: "1 bowl (150g)",
    calories: 280,
    protein: 14,
    carbs: 12,
    fat: 20,
    category: "Lunch/Dinner",
    fiber: 2.5,
    sugar: 4.0,
    sodium: 480,
    potassium: 180,
    vitaminA: 120,
    vitaminC: 6.8,
    calcium: 350,
    iron: 1.4
  },
  {
    id: "f8",
    name: "Palak Paneer",
    servingSize: "1 bowl (150g)",
    calories: 220,
    protein: 11,
    carbs: 8,
    fat: 16,
    category: "Lunch/Dinner",
    fiber: 3.8,
    sugar: 2.2,
    sodium: 420,
    potassium: 320,
    vitaminA: 340,
    vitaminC: 15,
    calcium: 380,
    iron: 2.8
  },
  {
    id: "f9",
    name: "Dal Tadka (Arhar/Toor)",
    servingSize: "1 bowl (150g)",
    calories: 150,
    protein: 7,
    carbs: 22,
    fat: 4,
    category: "Lunch/Dinner",
    fiber: 5.5,
    sugar: 0.6,
    sodium: 360,
    potassium: 290,
    vitaminA: 65,
    vitaminC: 2.4,
    calcium: 45,
    iron: 1.8
  },
  {
    id: "f10",
    name: "Dal Makhani",
    servingSize: "1 bowl (150g)",
    calories: 260,
    protein: 8.5,
    carbs: 28,
    fat: 13,
    category: "Lunch/Dinner",
    fiber: 6.2,
    sugar: 1.2,
    sodium: 490,
    potassium: 310,
    vitaminA: 95,
    vitaminC: 1.8,
    calcium: 90,
    iron: 2.2
  },

  // Indian Breakfasts
  {
    id: "f21",
    name: "Idli with Sambar",
    servingSize: "2 Idlis + Sambar",
    calories: 185,
    protein: 6.5,
    carbs: 36,
    fat: 2,
    category: "Breakfast",
    fiber: 4.0,
    sugar: 3.5,
    sodium: 410,
    potassium: 160,
    vitaminA: 35,
    vitaminC: 3.0,
    calcium: 55,
    iron: 1.1
  },
  {
    id: "f22",
    name: "Masala Dosa with Sambar",
    servingSize: "1 Dosa + Sambar",
    calories: 310,
    protein: 7.2,
    carbs: 54,
    fat: 7.5,
    category: "Breakfast",
    fiber: 4.8,
    sugar: 4.2,
    sodium: 590,
    potassium: 220,
    vitaminA: 40,
    vitaminC: 3.5,
    calcium: 68,
    iron: 1.4
  },
  {
    id: "f24",
    name: "Poha (With Peanuts)",
    servingSize: "1 plate (150g)",
    calories: 240,
    protein: 5,
    carbs: 40,
    fat: 6.5,
    category: "Breakfast",
    fiber: 2.8,
    sugar: 1.5,
    sodium: 310,
    potassium: 140,
    vitaminA: 15,
    vitaminC: 8.5,
    calcium: 38,
    iron: 2.1
  },

  // Dairy & High Protein Snacks
  {
    id: "f30",
    name: "Paneer (Raw, Low Fat)",
    servingSize: "100g",
    calories: 160,
    protein: 18,
    carbs: 2,
    fat: 9,
    category: "Dairy",
    fiber: 0,
    sugar: 1.8,
    sodium: 80,
    potassium: 95,
    vitaminA: 80,
    vitaminC: 0,
    calcium: 480,
    iron: 0.2
  },
  {
    id: "f35",
    name: "Whey Protein Isolate",
    servingSize: "1 Scoop (30g)",
    calories: 120,
    protein: 25,
    carbs: 1.5,
    fat: 1,
    category: "Snacks",
    fiber: 0.5,
    sugar: 0.5,
    sodium: 55,
    potassium: 160,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 140,
    iron: 0.1,
    brand: "Optimum Nutrition",
    barcode: "748927020084"
  },

  // Fruits
  {
    id: "f36",
    name: "Apple",
    servingSize: "1 Medium (150g)",
    calories: 80,
    protein: 0.4,
    carbs: 20,
    fat: 0.2,
    category: "Snacks",
    fiber: 4.4,
    sugar: 15,
    sodium: 1,
    potassium: 160,
    vitaminA: 8,
    vitaminC: 7.0,
    calcium: 9,
    iron: 0.2
  },
  {
    id: "f37",
    name: "Banana",
    servingSize: "1 Medium (100g)",
    calories: 90,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    category: "Snacks",
    fiber: 2.6,
    sugar: 12,
    sodium: 1,
    potassium: 360,
    vitaminA: 6,
    vitaminC: 8.7,
    calcium: 5,
    iron: 0.3
  },
  
  // Global Branded Fast Foods & Barcodes for scanning demos
  {
    id: "f38",
    name: "McDonalds Cheeseburger",
    servingSize: "1 Burger (120g)",
    calories: 300,
    protein: 16,
    carbs: 32,
    fat: 12,
    category: "Lunch/Dinner",
    fiber: 2.0,
    sugar: 7.0,
    sodium: 710,
    potassium: 230,
    vitaminA: 50,
    vitaminC: 1.2,
    calcium: 150,
    iron: 2.5,
    brand: "McDonalds",
    barcode: "0021000612239" // Seeded Barcode: Kraft/Cheeseburger context
  },
  {
    id: "f39",
    name: "McDonalds Chicken McNuggets",
    servingSize: "6 Pieces (100g)",
    calories: 270,
    protein: 15,
    carbs: 16,
    fat: 16,
    category: "Snacks",
    fiber: 1.0,
    sugar: 0,
    sodium: 540,
    potassium: 190,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 15,
    iron: 0.6,
    brand: "McDonalds",
    barcode: "044000031226"
  },
  {
    id: "f40",
    name: "Starbucks Iced Caffe Latte (Grande)",
    servingSize: "1 cup (473ml)",
    calories: 130,
    protein: 8,
    carbs: 13,
    fat: 4.5,
    category: "Other",
    fiber: 0,
    sugar: 11,
    sodium: 115,
    potassium: 380,
    vitaminA: 150,
    vitaminC: 0,
    calcium: 300,
    iron: 0.1,
    brand: "Starbucks",
    barcode: "8801043014847" // Seeded Barcode: Latte Pack context
  },
  {
    id: "f42",
    name: "Pizza Hut Pepperoni Pizza (Personal)",
    servingSize: "1 Pizza (200g)",
    calories: 590,
    protein: 26,
    carbs: 64,
    fat: 25,
    category: "Lunch/Dinner",
    fiber: 3.5,
    sugar: 5.5,
    sodium: 1280,
    potassium: 390,
    vitaminA: 160,
    vitaminC: 4.8,
    calcium: 280,
    iron: 4.2,
    brand: "Pizza Hut",
    barcode: "075900001859"
  },
  {
    id: "f45",
    name: "Coca-Cola (Regular)",
    servingSize: "1 Can (330ml)",
    calories: 139,
    protein: 0,
    carbs: 35,
    fat: 0,
    category: "Other",
    fiber: 0,
    sugar: 35,
    sodium: 15,
    potassium: 10,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 0,
    iron: 0,
    brand: "Coca-Cola",
    barcode: "5449000000996"
  },
  {
    id: "f46",
    name: "Diet Coke / Coke Zero",
    servingSize: "1 Can (330ml)",
    calories: 1,
    protein: 0,
    carbs: 0,
    fat: 0,
    category: "Other",
    fiber: 0,
    sugar: 0,
    sodium: 40,
    potassium: 15,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 0,
    iron: 0,
    brand: "Coca-Cola",
    barcode: "5449000133335"
  }
];
