/**
 * Pre-seeded Indian & Global Food Database
 * Extended with full macro, micronutrient, and metadata profiles.
 */

export interface FoodItem {
  id: string;
  name: string;
  servingSize: string;
  calories: number;
  protein: number; // in grams
  carbs: number;   // in grams
  fat: number;     // in grams
  category: "Breakfast" | "Lunch/Dinner" | "Snacks" | "Dairy" | "Breads" | "Other";
  fiber?: number;      // in grams
  sugar?: number;      // in grams
  sodium?: number;     // in milligrams
  potassium?: number;  // in milligrams
  cholesterol?: number;// in milligrams
  vitaminA?: number;   // in mcg RAE
  vitaminC?: number;   // in mg
  calcium?: number;    // in mg
  iron?: number;       // in mg
  barcode?: string;    // Barcode for barcode scanner lookup
  brand?: string;      // Brand name
  country?: string;    // "IN" | "Global" | "US"
  aliases?: string[];  // Synonym lookups (e.g. curd = dahi)
  popularityScore?: number; // 0-100 (for search ranking)
  verificationStatus?: "Verified" | "User-Submitted" | "Pending";
}

export const INITIAL_FOODS: FoodItem[] = [
  // ==========================================
  // INDIAN HOME-COOKED & REGIONAL DISHES
  // ==========================================
  {
    id: "in-roti",
    name: "Whole Wheat Roti / Chapati",
    servingSize: "1 Roti (35g)",
    calories: 85,
    protein: 3,
    carbs: 18,
    fat: 0.5,
    category: "Breads",
    fiber: 2.2,
    sugar: 0.2,
    sodium: 120,
    potassium: 90,
    cholesterol: 0,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 15,
    iron: 0.8,
    country: "IN",
    aliases: ["chapati", "phulka", "roti", "wheat flatbread", "chappati"],
    popularityScore: 98,
    verificationStatus: "Verified"
  },
  {
    id: "in-butter-roti",
    name: "Butter Roti / Chapati",
    servingSize: "1 Roti (40g)",
    calories: 120,
    protein: 3.2,
    carbs: 18,
    fat: 3.5,
    category: "Breads",
    fiber: 2.2,
    sugar: 0.2,
    sodium: 150,
    potassium: 92,
    cholesterol: 8,
    vitaminA: 25,
    vitaminC: 0,
    calcium: 18,
    iron: 0.8,
    country: "IN",
    aliases: ["ghee roti", "butter chapati", "roti with ghee"],
    popularityScore: 90,
    verificationStatus: "Verified"
  },
  {
    id: "in-plain-paratha",
    name: "Plain Paratha",
    servingSize: "1 Paratha (60g)",
    calories: 258,
    protein: 4.5,
    carbs: 32,
    fat: 12,
    category: "Breads",
    fiber: 3.5,
    sugar: 0.4,
    sodium: 280,
    potassium: 110,
    cholesterol: 10,
    vitaminA: 40,
    vitaminC: 0,
    calcium: 22,
    iron: 1.2,
    country: "IN",
    aliases: ["parantha", "parotta", "plain parantha"],
    popularityScore: 85,
    verificationStatus: "Verified"
  },
  {
    id: "in-aloo-paratha",
    name: "Aloo Paratha",
    servingSize: "1 Paratha (90g)",
    calories: 290,
    protein: 5.2,
    carbs: 42,
    fat: 11,
    category: "Breads",
    fiber: 4.2,
    sugar: 0.8,
    sodium: 380,
    potassium: 240,
    cholesterol: 12,
    vitaminA: 45,
    vitaminC: 4.5,
    calcium: 30,
    iron: 1.5,
    country: "IN",
    aliases: ["potato paratha", "aloo parantha", "alu paratha"],
    popularityScore: 95,
    verificationStatus: "Verified"
  },
  {
    id: "in-gobhi-paratha",
    name: "Gobhi Paratha",
    servingSize: "1 Paratha (90g)",
    calories: 210,
    protein: 4.8,
    carbs: 34,
    fat: 6.2,
    category: "Breads",
    fiber: 3.8,
    sugar: 1.1,
    sodium: 360,
    potassium: 190,
    cholesterol: 5,
    vitaminA: 35,
    vitaminC: 8.2,
    calcium: 28,
    iron: 1.3,
    country: "IN",
    aliases: ["cauliflower paratha", "gobi parantha", "gobhi parantha"],
    popularityScore: 80,
    verificationStatus: "Verified"
  },
  {
    id: "in-paneer-paratha",
    name: "Paneer Paratha",
    servingSize: "1 Paratha (100g)",
    calories: 320,
    protein: 12.5,
    carbs: 36,
    fat: 14.2,
    category: "Breads",
    fiber: 3.1,
    sugar: 1.5,
    sodium: 410,
    potassium: 160,
    cholesterol: 25,
    vitaminA: 110,
    vitaminC: 1.5,
    calcium: 180,
    iron: 1.6,
    country: "IN",
    aliases: ["cottage cheese paratha", "paneer parantha"],
    popularityScore: 88,
    verificationStatus: "Verified"
  },
  {
    id: "in-basmati-rice",
    name: "Steamed Basmati Rice",
    servingSize: "1 bowl (150g)",
    calories: 195,
    protein: 4.3,
    carbs: 44,
    fat: 0.4,
    category: "Lunch/Dinner",
    fiber: 1.1,
    sugar: 0.1,
    sodium: 5,
    potassium: 45,
    cholesterol: 0,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 10,
    iron: 0.6,
    country: "IN",
    aliases: ["boiled rice", "cooked basmati rice", "white rice", "chawal"],
    popularityScore: 97,
    verificationStatus: "Verified"
  },
  {
    id: "in-jeera-rice",
    name: "Jeera Rice",
    servingSize: "1 bowl (150g)",
    calories: 225,
    protein: 4.5,
    carbs: 45,
    fat: 3.2,
    category: "Lunch/Dinner",
    fiber: 1.5,
    sugar: 0.2,
    sodium: 220,
    potassium: 60,
    cholesterol: 5,
    vitaminA: 10,
    vitaminC: 0,
    calcium: 20,
    iron: 0.9,
    country: "IN",
    aliases: ["cumin rice", "jeera chawal"],
    popularityScore: 78,
    verificationStatus: "Verified"
  },
  {
    id: "in-veg-pulao",
    name: "Vegetable Pulao",
    servingSize: "1 bowl (200g)",
    calories: 280,
    protein: 6.2,
    carbs: 52,
    fat: 5.8,
    category: "Lunch/Dinner",
    fiber: 3.4,
    sugar: 1.8,
    sodium: 380,
    potassium: 150,
    cholesterol: 0,
    vitaminA: 120,
    vitaminC: 8.5,
    calcium: 35,
    iron: 1.4,
    country: "IN",
    aliases: ["pulav", "veg pilaf", "vegetable pulao", "pilav"],
    popularityScore: 82,
    verificationStatus: "Verified"
  },
  {
    id: "in-veg-biryani",
    name: "Veg Biryani (Hyderabadi)",
    servingSize: "1 plate (300g)",
    calories: 420,
    protein: 9.8,
    carbs: 72,
    fat: 10.5,
    category: "Lunch/Dinner",
    fiber: 4.8,
    sugar: 3.0,
    sodium: 680,
    potassium: 290,
    cholesterol: 15,
    vitaminA: 180,
    vitaminC: 12.0,
    calcium: 95,
    iron: 2.1,
    country: "IN",
    aliases: ["vegetable biryani", "biryani veg", "hyderabadi veg biryani"],
    popularityScore: 92,
    verificationStatus: "Verified"
  },
  {
    id: "in-chicken-biryani",
    name: "Chicken Biryani",
    servingSize: "1 plate (350g)",
    calories: 540,
    protein: 28.5,
    carbs: 75,
    fat: 14.8,
    category: "Lunch/Dinner",
    fiber: 3.5,
    sugar: 2.1,
    sodium: 840,
    potassium: 420,
    cholesterol: 75,
    vitaminA: 90,
    vitaminC: 6.0,
    calcium: 60,
    iron: 2.8,
    country: "IN",
    aliases: ["murgh biryani", "non veg biryani", "chicken chawal biryani"],
    popularityScore: 97,
    verificationStatus: "Verified"
  },
  {
    id: "in-dal-tadka",
    name: "Dal Tadka (Arhar/Toor Dal)",
    servingSize: "1 bowl (150g)",
    calories: 150,
    protein: 7,
    carbs: 22,
    fat: 4,
    category: "Lunch/Dinner",
    fiber: 5.5,
    sugar: 0.6,
    sodium: 360,
    potassium: 290,
    cholesterol: 5,
    vitaminA: 65,
    vitaminC: 2.4,
    calcium: 45,
    iron: 1.8,
    country: "IN",
    aliases: ["toor dal", "yellow dal", "arhar dal", "lentil curry", "dal fry"],
    popularityScore: 94,
    verificationStatus: "Verified"
  },
  {
    id: "in-dal-makhani",
    name: "Dal Makhani",
    servingSize: "1 bowl (150g)",
    calories: 260,
    protein: 8.5,
    carbs: 28,
    fat: 13,
    category: "Lunch/Dinner",
    fiber: 6.2,
    sugar: 1.2,
    sodium: 490,
    potassium: 310,
    cholesterol: 32,
    vitaminA: 95,
    vitaminC: 1.8,
    calcium: 90,
    iron: 2.2,
    country: "IN",
    aliases: ["black dal", "creamy lentils", "dal makhani curry"],
    popularityScore: 89,
    verificationStatus: "Verified"
  },
  {
    id: "in-rajma-curry",
    name: "Rajma Masala (Kidney Bean Curry)",
    servingSize: "1 bowl (150g)",
    calories: 180,
    protein: 8.2,
    carbs: 26,
    fat: 4.8,
    category: "Lunch/Dinner",
    fiber: 7.1,
    sugar: 1.5,
    sodium: 390,
    potassium: 380,
    cholesterol: 0,
    vitaminA: 80,
    vitaminC: 5.2,
    calcium: 60,
    iron: 2.5,
    country: "IN",
    aliases: ["rajma chawal", "kidney beans", "rajmah"],
    popularityScore: 93,
    verificationStatus: "Verified"
  },
  {
    id: "in-chole-masala",
    name: "Chole Masala (Chickpea Curry)",
    servingSize: "1 bowl (150g)",
    calories: 195,
    protein: 8.5,
    carbs: 29,
    fat: 5.2,
    category: "Lunch/Dinner",
    fiber: 6.8,
    sugar: 1.9,
    sodium: 420,
    potassium: 310,
    cholesterol: 0,
    vitaminA: 70,
    vitaminC: 6.4,
    calcium: 75,
    iron: 2.8,
    country: "IN",
    aliases: ["chana masala", "chole bhature curry", "choley", "chickpeas"],
    popularityScore: 91,
    verificationStatus: "Verified"
  },
  {
    id: "in-chole-bhature",
    name: "Chole Bhature Combo",
    servingSize: "1 Plate (2 Bhature + Chole)",
    calories: 620,
    protein: 15.5,
    carbs: 78,
    fat: 27.5,
    category: "Lunch/Dinner",
    fiber: 7.5,
    sugar: 4.0,
    sodium: 980,
    potassium: 360,
    cholesterol: 20,
    vitaminA: 110,
    vitaminC: 8.0,
    calcium: 120,
    iron: 4.5,
    country: "IN",
    aliases: ["chola bhatura", "bhature chole", "fried bread with chickpeas"],
    popularityScore: 94,
    verificationStatus: "Verified"
  },
  {
    id: "in-khichdi",
    name: "Moong Dal Khichdi",
    servingSize: "1 bowl (200g)",
    calories: 230,
    protein: 8.2,
    carbs: 42,
    fat: 3.5,
    category: "Lunch/Dinner",
    fiber: 4.5,
    sugar: 0.5,
    sodium: 320,
    potassium: 220,
    cholesterol: 5,
    vitaminA: 40,
    vitaminC: 1.5,
    calcium: 38,
    iron: 1.9,
    country: "IN",
    aliases: ["kitchari", "khichri", "lentil rice porridge", "moong khichdi"],
    popularityScore: 89,
    verificationStatus: "Verified"
  },
  {
    id: "in-bhindi-masala",
    name: "Bhindi Sabzi (Okra Fry)",
    servingSize: "1 bowl (150g)",
    calories: 110,
    protein: 2.5,
    carbs: 11,
    fat: 6.5,
    category: "Lunch/Dinner",
    fiber: 3.8,
    sugar: 1.5,
    sodium: 290,
    potassium: 260,
    cholesterol: 0,
    vitaminA: 95,
    vitaminC: 18.0,
    calcium: 72,
    iron: 1.1,
    country: "IN",
    aliases: ["okra curry", "bhindi fry", "lady finger sabji"],
    popularityScore: 84,
    verificationStatus: "Verified"
  },
  {
    id: "in-aloo-gobi",
    name: "Aloo Gobi Sabzi",
    servingSize: "1 bowl (150g)",
    calories: 145,
    protein: 3.2,
    carbs: 16,
    fat: 8.0,
    category: "Lunch/Dinner",
    fiber: 3.2,
    sugar: 2.0,
    sodium: 310,
    potassium: 340,
    cholesterol: 0,
    vitaminA: 55,
    vitaminC: 22.0,
    calcium: 35,
    iron: 1.4,
    country: "IN",
    aliases: ["potato cauliflower sabji", "aloo gobhi", "alu gobi"],
    popularityScore: 86,
    verificationStatus: "Verified"
  },
  {
    id: "in-aloo-sabzi",
    name: "Aloo Sabzi (Potato Curry)",
    servingSize: "1 bowl (150g)",
    calories: 135,
    protein: 2.5,
    carbs: 22.0,
    fat: 4.5,
    category: "Lunch/Dinner",
    fiber: 3.0,
    sugar: 1.5,
    sodium: 350,
    potassium: 390,
    cholesterol: 0,
    vitaminA: 40,
    vitaminC: 15.0,
    calcium: 20,
    iron: 1.1,
    country: "IN",
    aliases: ["aloo sabji", "potato curry", "alu sabzi", "potato sabji"],
    popularityScore: 90,
    verificationStatus: "Verified"
  },
  {
    id: "in-shahi-paneer",
    name: "Shahi Paneer",
    servingSize: "1 bowl (150g)",
    calories: 310,
    protein: 13.5,
    carbs: 14,
    fat: 23,
    category: "Lunch/Dinner",
    fiber: 1.8,
    sugar: 5.5,
    sodium: 460,
    potassium: 190,
    cholesterol: 45,
    vitaminA: 210,
    vitaminC: 4.2,
    calcium: 390,
    iron: 1.2,
    country: "IN",
    aliases: ["royal cottage cheese", "rich paneer curry", "creamy paneer"],
    popularityScore: 93,
    verificationStatus: "Verified"
  },
  {
    id: "in-paneer-butter",
    name: "Paneer Butter Masala",
    servingSize: "1 bowl (150g)",
    calories: 340,
    protein: 14.0,
    carbs: 12,
    fat: 26,
    category: "Lunch/Dinner",
    fiber: 2.0,
    sugar: 4.8,
    sodium: 480,
    potassium: 180,
    cholesterol: 55,
    vitaminA: 240,
    vitaminC: 3.8,
    calcium: 410,
    iron: 1.4,
    country: "IN",
    aliases: ["paneer tikka masala", "cottage cheese butter curry", "butter paneer"],
    popularityScore: 96,
    verificationStatus: "Verified"
  },
  {
    id: "in-palak-paneer",
    name: "Palak Paneer",
    servingSize: "1 bowl (150g)",
    calories: 220,
    protein: 11,
    carbs: 8,
    fat: 16,
    category: "Lunch/Dinner",
    fiber: 3.8,
    sugar: 2.2,
    sodium: 420,
    potassium: 320,
    cholesterol: 30,
    vitaminA: 340,
    vitaminC: 15,
    calcium: 380,
    iron: 2.8,
    country: "IN",
    aliases: ["spinach paneer", "palac paneer", "spinach cottage cheese"],
    popularityScore: 94,
    verificationStatus: "Verified"
  },
  {
    id: "in-paneer-bhurji",
    name: "Paneer Bhurji",
    servingSize: "1 plate (150g)",
    calories: 275,
    protein: 16.5,
    carbs: 7.5,
    fat: 20.5,
    category: "Breakfast",
    fiber: 2.1,
    sugar: 1.8,
    sodium: 390,
    potassium: 175,
    cholesterol: 40,
    vitaminA: 180,
    vitaminC: 9.5,
    calcium: 340,
    iron: 1.5,
    country: "IN",
    aliases: ["scrambled paneer", "paneer scramble", "bhurjee"],
    popularityScore: 89,
    verificationStatus: "Verified"
  },
  {
    id: "in-kadhi-pakora",
    name: "Punjabi Kadhi Pakora",
    servingSize: "1 bowl (200g)",
    calories: 210,
    protein: 6.8,
    carbs: 24,
    fat: 10.2,
    category: "Lunch/Dinner",
    fiber: 3.5,
    sugar: 2.8,
    sodium: 540,
    potassium: 205,
    cholesterol: 8,
    vitaminA: 85,
    vitaminC: 3.0,
    calcium: 120,
    iron: 1.8,
    country: "IN",
    aliases: ["kadhi pakoda", "besan kadhi", "yogurt gramflour curry"],
    popularityScore: 85,
    verificationStatus: "Verified"
  },
  {
    id: "in-lassi-sweet",
    name: "Sweet Lassi",
    servingSize: "1 glass (250ml)",
    calories: 210,
    protein: 5.5,
    carbs: 32,
    fat: 6.5,
    category: "Other",
    fiber: 0,
    sugar: 28,
    sodium: 85,
    potassium: 180,
    cholesterol: 18,
    vitaminA: 90,
    vitaminC: 1.2,
    calcium: 210,
    iron: 0.1,
    country: "IN",
    aliases: ["sweetened yogurt drink", "lassi", "punjabi lassi"],
    popularityScore: 88,
    verificationStatus: "Verified"
  },
  {
    id: "in-buttermilk",
    name: "Spiced Buttermilk (Chaas)",
    servingSize: "1 glass (200ml)",
    calories: 45,
    protein: 2.2,
    carbs: 3.8,
    fat: 2.2,
    category: "Other",
    fiber: 0,
    sugar: 3.2,
    sodium: 280,
    potassium: 120,
    cholesterol: 5,
    vitaminA: 40,
    vitaminC: 0.8,
    calcium: 110,
    iron: 0.1,
    country: "IN",
    aliases: ["chaas", "chhaas", "salt lassi", "matha", "takk"],
    popularityScore: 92,
    verificationStatus: "Verified"
  },
  {
    id: "in-poha",
    name: "Indori Poha (With Peanuts & Sev)",
    servingSize: "1 plate (150g)",
    calories: 260,
    protein: 5.5,
    carbs: 42,
    fat: 7.8,
    category: "Breakfast",
    fiber: 2.8,
    sugar: 1.8,
    sodium: 380,
    potassium: 155,
    cholesterol: 0,
    vitaminA: 20,
    vitaminC: 12.0,
    calcium: 40,
    iron: 2.3,
    country: "IN",
    aliases: ["flattened rice", "pohe", "pua", "aval"],
    popularityScore: 95,
    verificationStatus: "Verified"
  },
  {
    id: "in-upma",
    name: "Suji Upma (Semolina Savory Porridge)",
    servingSize: "1 plate (150g)",
    calories: 190,
    protein: 4.8,
    carbs: 31,
    fat: 5.0,
    category: "Breakfast",
    fiber: 2.2,
    sugar: 0.8,
    sodium: 290,
    potassium: 90,
    cholesterol: 2,
    vitaminA: 15,
    vitaminC: 2.5,
    calcium: 22,
    iron: 1.1,
    country: "IN",
    aliases: ["uppuma", "ravva upma", "semolina breakfast"],
    popularityScore: 90,
    verificationStatus: "Verified"
  },
  {
    id: "in-idli-sambar",
    name: "Steamed Idli with Sambar",
    servingSize: "2 Idlis + Sambar (150g)",
    calories: 185,
    protein: 6.5,
    carbs: 36,
    fat: 2.0,
    category: "Breakfast",
    fiber: 4.0,
    sugar: 3.5,
    sodium: 410,
    potassium: 160,
    cholesterol: 0,
    vitaminA: 35,
    vitaminC: 3.0,
    calcium: 55,
    iron: 1.1,
    country: "IN",
    aliases: ["idly", "rice cakes with sambar", "south indian idli"],
    popularityScore: 96,
    verificationStatus: "Verified"
  },
  {
    id: "in-masala-dosa",
    name: "Masala Dosa with Sambar & Chutney",
    servingSize: "1 Dosa + Sambar + Chutney (220g)",
    calories: 380,
    protein: 8.5,
    carbs: 62,
    fat: 10.5,
    category: "Breakfast",
    fiber: 5.5,
    sugar: 4.5,
    sodium: 720,
    potassium: 270,
    cholesterol: 0,
    vitaminA: 45,
    vitaminC: 4.2,
    calcium: 82,
    iron: 1.8,
    country: "IN",
    aliases: ["dosa", "dhosa", "masala dosha", "potato crepe"],
    popularityScore: 97,
    verificationStatus: "Verified"
  },
  {
    id: "in-uttapam",
    name: "Onion Tomato Uttapam",
    servingSize: "1 Uttapam (150g)",
    calories: 240,
    protein: 5.8,
    carbs: 44,
    fat: 4.5,
    category: "Breakfast",
    fiber: 3.2,
    sugar: 2.8,
    sodium: 480,
    potassium: 140,
    cholesterol: 0,
    vitaminA: 60,
    vitaminC: 7.2,
    calcium: 45,
    iron: 1.4,
    country: "IN",
    aliases: ["uttappa", "oothapam", "south indian pancake"],
    popularityScore: 84,
    verificationStatus: "Verified"
  },
  {
    id: "in-medu-vada",
    name: "Medu Vada (Fried Lentil Donuts)",
    servingSize: "2 pieces (80g)",
    calories: 270,
    protein: 6.8,
    carbs: 28,
    fat: 14.5,
    category: "Breakfast",
    fiber: 3.0,
    sugar: 0.5,
    sodium: 390,
    potassium: 185,
    cholesterol: 0,
    vitaminA: 10,
    vitaminC: 1.2,
    calcium: 32,
    iron: 1.5,
    country: "IN",
    aliases: ["vada", "uddina vada", "wada", "medhu vadai"],
    popularityScore: 87,
    verificationStatus: "Verified"
  },
  {
    id: "in-dhokla",
    name: "Khaman Dhokla",
    servingSize: "3 pieces (100g)",
    calories: 160,
    protein: 6.2,
    carbs: 26,
    fat: 3.2,
    category: "Breakfast",
    fiber: 2.4,
    sugar: 6.5,
    sodium: 480,
    potassium: 110,
    cholesterol: 0,
    vitaminA: 15,
    vitaminC: 1.8,
    calcium: 42,
    iron: 1.6,
    country: "IN",
    aliases: ["khaman", "gujarati dhokla", "steamed gramflour cake"],
    popularityScore: 88,
    verificationStatus: "Verified"
  },
  {
    id: "in-pav-bhaji",
    name: "Pav Bhaji",
    servingSize: "1 plate (2 Pav + Bhaji)",
    calories: 460,
    protein: 9.5,
    carbs: 68,
    fat: 16.5,
    category: "Lunch/Dinner",
    fiber: 5.8,
    sugar: 6.2,
    sodium: 890,
    potassium: 340,
    cholesterol: 25,
    vitaminA: 190,
    vitaminC: 14.0,
    calcium: 88,
    iron: 2.9,
    country: "IN",
    aliases: ["pavbhaji", "butter pav bhaji", "mumbai street pav bhaji"],
    popularityScore: 95,
    verificationStatus: "Verified"
  },
  {
    id: "in-vada-pav",
    name: "Vada Pav",
    servingSize: "1 piece (120g)",
    calories: 290,
    protein: 6.0,
    carbs: 45,
    fat: 9.8,
    category: "Snacks",
    fiber: 2.8,
    sugar: 4.2,
    sodium: 580,
    potassium: 190,
    cholesterol: 0,
    vitaminA: 25,
    vitaminC: 3.2,
    calcium: 38,
    iron: 1.8,
    country: "IN",
    aliases: ["vadapav", "bombay burger", "wada pav"],
    popularityScore: 94,
    verificationStatus: "Verified"
  },
  {
    id: "in-pani-puri",
    name: "Pani Puri / Golgappa",
    servingSize: "6 pieces (120g)",
    calories: 180,
    protein: 3.5,
    carbs: 32,
    fat: 4.2,
    category: "Snacks",
    fiber: 2.5,
    sugar: 2.0,
    sodium: 620,
    potassium: 150,
    cholesterol: 0,
    vitaminA: 35,
    vitaminC: 5.5,
    calcium: 25,
    iron: 1.4,
    country: "IN",
    aliases: ["golgappa", "puchka", "gol gappa", "gupchup", "pani poori"],
    popularityScore: 96,
    verificationStatus: "Verified"
  },
  {
    id: "in-samosa",
    name: "Samosa (Potato Filled)",
    servingSize: "1 medium samosa (80g)",
    calories: 250,
    protein: 3.8,
    carbs: 31,
    fat: 12.5,
    category: "Snacks",
    fiber: 2.1,
    sugar: 1.2,
    sodium: 380,
    potassium: 140,
    cholesterol: 0,
    vitaminA: 15,
    vitaminC: 4.5,
    calcium: 18,
    iron: 1.1,
    country: "IN",
    aliases: ["singara", "sambosa", "punjabi samosa", "fried potato pastry"],
    popularityScore: 96,
    verificationStatus: "Verified"
  },

  // ==========================================
  // INDIAN BRANDS & PRODUCTS
  // ==========================================
  {
    id: "brand-amul-butter",
    name: "Amul Pasteurized Butter",
    servingSize: "1 tbsp (10g)",
    calories: 72,
    protein: 0.1,
    carbs: 0.1,
    fat: 8.0,
    category: "Dairy",
    fiber: 0,
    sugar: 0,
    sodium: 83,
    potassium: 2,
    cholesterol: 22,
    vitaminA: 75,
    vitaminC: 0,
    calcium: 2,
    iron: 0,
    brand: "Amul",
    barcode: "8901262010118",
    country: "IN",
    aliases: ["amul makhan", "salted butter", "butter amul"],
    popularityScore: 97,
    verificationStatus: "Verified"
  },
  {
    id: "brand-amul-paneer",
    name: "Amul Fresh Paneer",
    servingSize: "100g",
    calories: 290,
    protein: 20.0,
    carbs: 2.0,
    fat: 22.8,
    category: "Dairy",
    fiber: 0,
    sugar: 1.5,
    sodium: 45,
    potassium: 90,
    cholesterol: 60,
    vitaminA: 150,
    vitaminC: 0,
    calcium: 480,
    iron: 0.2,
    brand: "Amul",
    barcode: "8901262060120",
    country: "IN",
    aliases: ["amul cottage cheese", "fresh paneer block"],
    popularityScore: 98,
    verificationStatus: "Verified"
  },
  {
    id: "brand-amul-masti",
    name: "Amul Masti Spiced Buttermilk",
    servingSize: "1 pack (200ml)",
    calories: 30,
    protein: 1.6,
    carbs: 2.2,
    fat: 1.6,
    category: "Dairy",
    fiber: 0,
    sugar: 0,
    sodium: 220,
    potassium: 90,
    cholesterol: 4,
    vitaminA: 35,
    vitaminC: 0.5,
    calcium: 85,
    iron: 0.1,
    brand: "Amul",
    barcode: "8901262151040",
    country: "IN",
    aliases: ["masti chaas", "amul chaas", "spiced buttermilk pack"],
    popularityScore: 94,
    verificationStatus: "Verified"
  },
  {
    id: "brand-amul-curd",
    name: "Amul Masti Dahi / Curd",
    servingSize: "1 container (200g)",
    calories: 120,
    protein: 6.4,
    carbs: 8.8,
    fat: 6.4,
    category: "Dairy",
    fiber: 0,
    sugar: 4.8,
    sodium: 90,
    potassium: 280,
    cholesterol: 18,
    vitaminA: 95,
    vitaminC: 1.0,
    calcium: 240,
    iron: 0.2,
    brand: "Amul",
    barcode: "8901262150128",
    country: "IN",
    aliases: ["amul curd", "amul dahi", "dahi amul", "curd amul", "masti dahi"],
    popularityScore: 97,
    verificationStatus: "Verified"
  },
  {
    id: "brand-epigamia-yogurt",
    name: "Epigamia Natural Greek Yogurt",
    servingSize: "1 cup (90g)",
    calories: 78,
    protein: 7.2,
    carbs: 4.5,
    fat: 3.6,
    category: "Dairy",
    fiber: 0,
    sugar: 3.2,
    sodium: 40,
    potassium: 120,
    cholesterol: 10,
    vitaminA: 25,
    vitaminC: 0,
    calcium: 150,
    iron: 0.1,
    brand: "Epigamia",
    barcode: "8906070630048",
    country: "IN",
    aliases: ["epigamia greek yogurt", "high protein yogurt", "greek curd"],
    popularityScore: 92,
    verificationStatus: "Verified"
  },
  {
    id: "brand-mother-dairy",
    name: "Mother Dairy Full Cream Milk",
    servingSize: "1 glass (200ml)",
    calories: 118,
    protein: 6.4,
    carbs: 9.6,
    fat: 6.0,
    category: "Dairy",
    fiber: 0,
    sugar: 9.6,
    sodium: 100,
    potassium: 300,
    cholesterol: 16,
    vitaminA: 110,
    vitaminC: 2.0,
    calcium: 220,
    iron: 0.1,
    brand: "Mother Dairy",
    barcode: "8902095000030",
    country: "IN",
    aliases: ["mother dairy milk", "full cream milk packet"],
    popularityScore: 95,
    verificationStatus: "Verified"
  },
  {
    id: "brand-britannia-marie",
    name: "Britannia Marie Gold Biscuit",
    servingSize: "4 biscuits (30g)",
    calories: 135,
    protein: 2.2,
    carbs: 24.3,
    fat: 3.2,
    category: "Snacks",
    fiber: 0.8,
    sugar: 6.8,
    sodium: 115,
    potassium: 40,
    cholesterol: 0,
    vitaminA: 10,
    vitaminC: 0,
    calcium: 12,
    iron: 0.6,
    brand: "Britannia",
    barcode: "8901063142278",
    country: "IN",
    aliases: ["marie gold", "marie biscuit", "tea time gold biscuit"],
    popularityScore: 94,
    verificationStatus: "Verified"
  },
  {
    id: "brand-muscleblaze-whey",
    name: "MuscleBlaze Biozyme Whey Protein",
    servingSize: "1 scoop (36g)",
    calories: 140,
    protein: 25.0,
    carbs: 3.2,
    fat: 1.8,
    category: "Snacks",
    fiber: 0.5,
    sugar: 0,
    sodium: 85,
    potassium: 190,
    cholesterol: 10,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 150,
    iron: 0.3,
    brand: "MuscleBlaze",
    barcode: "8906067026564",
    country: "IN",
    aliases: ["mb whey", "muscleblaze protein", "mb biozyme"],
    popularityScore: 93,
    verificationStatus: "Verified"
  },
  {
    id: "brand-wholetruth-bar",
    name: "The Whole Truth Peanut Cocoa Bar",
    servingSize: "1 bar (40g)",
    calories: 198,
    protein: 6.2,
    carbs: 18.4,
    fat: 10.8,
    category: "Snacks",
    fiber: 3.2,
    sugar: 12.0,
    sodium: 40,
    potassium: 210,
    cholesterol: 0,
    vitaminA: 0,
    vitaminC: 1.2,
    calcium: 45,
    iron: 1.1,
    brand: "The Whole Truth",
    barcode: "8908013327117",
    country: "IN",
    aliases: ["twt protein bar", "whole truth energy bar", "peanut cocoa"],
    popularityScore: 89,
    verificationStatus: "Verified"
  },

  // ==========================================
  // GLOBAL BRANDS & PACKAGED PRODUCTS
  // ==========================================
  {
    id: "brand-coca-cola",
    name: "Coca-Cola Classic",
    servingSize: "1 Can (330ml)",
    calories: 139,
    protein: 0,
    carbs: 35,
    fat: 0,
    category: "Other",
    fiber: 0,
    sugar: 35,
    sodium: 15,
    potassium: 10,
    cholesterol: 0,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 0,
    iron: 0,
    brand: "Coca-Cola",
    barcode: "5449000000996",
    country: "Global",
    aliases: ["coke", "coca cola", "soda", "cold drink", "sweet beverage", "soft drink"],
    popularityScore: 99,
    verificationStatus: "Verified"
  },
  {
    id: "brand-coke-zero",
    name: "Coca-Cola Zero Sugar",
    servingSize: "1 Can (330ml)",
    calories: 1,
    protein: 0,
    carbs: 0,
    fat: 0,
    category: "Other",
    fiber: 0,
    sugar: 0,
    sodium: 40,
    potassium: 15,
    cholesterol: 0,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 0,
    iron: 0,
    brand: "Coca-Cola",
    barcode: "5449000133335",
    country: "Global",
    aliases: ["diet coke", "coke zero", "sugar free soda", "zero coke"],
    popularityScore: 98,
    verificationStatus: "Verified"
  },
  {
    id: "brand-red-bull",
    name: "Red Bull Energy Drink",
    servingSize: "1 Can (250ml)",
    calories: 110,
    protein: 1.0,
    carbs: 26,
    fat: 0,
    category: "Other",
    fiber: 0,
    sugar: 26,
    sodium: 80,
    potassium: 15,
    cholesterol: 0,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 0,
    iron: 0,
    brand: "Red Bull",
    barcode: "9002490100070",
    country: "Global",
    aliases: ["redbull", "energy drink", "caffeinated drink"],
    popularityScore: 96,
    verificationStatus: "Verified"
  },
  {
    id: "brand-oreo",
    name: "Oreo Chocolate Sandwich Cookies",
    servingSize: "3 cookies (29g)",
    calories: 140,
    protein: 1.0,
    carbs: 21,
    fat: 6.0,
    category: "Snacks",
    fiber: 1.0,
    sugar: 13.0,
    sodium: 135,
    potassium: 45,
    cholesterol: 0,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 10,
    iron: 1.8,
    brand: "Oreo",
    barcode: "044000031226",
    country: "Global",
    aliases: ["oreo biscuit", "chocolate cookies", "oreos"],
    popularityScore: 98,
    verificationStatus: "Verified"
  },
  {
    id: "brand-on-whey",
    name: "Optimum Nutrition 100% Whey Gold Standard",
    servingSize: "1 Scoop (30g)",
    calories: 120,
    protein: 24.0,
    carbs: 3.0,
    fat: 1.0,
    category: "Snacks",
    fiber: 0,
    sugar: 1.0,
    sodium: 130,
    potassium: 220,
    cholesterol: 30,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 130,
    iron: 0,
    brand: "Optimum Nutrition",
    barcode: "748927020084",
    country: "Global",
    aliases: ["on whey protein", "gold standard whey", "double rich chocolate"],
    popularityScore: 96,
    verificationStatus: "Verified"
  },

  // ==========================================
  // RESTAURANTS & FAST FOOD CHAINS
  // ==========================================
  {
    id: "rest-mcd-cheeseburger",
    name: "McDonald's Cheeseburger",
    servingSize: "1 Burger (119g)",
    calories: 300,
    protein: 15.0,
    carbs: 32.0,
    fat: 12.0,
    category: "Lunch/Dinner",
    fiber: 2.0,
    sugar: 7.0,
    sodium: 720,
    potassium: 230,
    cholesterol: 40,
    vitaminA: 50,
    vitaminC: 1.2,
    calcium: 150,
    iron: 2.5,
    brand: "McDonalds",
    barcode: "0021000612239",
    country: "Global",
    aliases: ["mcd cheeseburger", "mcdonalds cheese burger", "double cheese mcd"],
    popularityScore: 97,
    verificationStatus: "Verified"
  },
  {
    id: "rest-mcd-mcspicy",
    name: "McDonald's McSpicy Chicken Burger",
    servingSize: "1 Burger (180g)",
    calories: 490,
    protein: 22.5,
    carbs: 48.0,
    fat: 22.0,
    category: "Lunch/Dinner",
    fiber: 3.2,
    sugar: 6.8,
    sodium: 980,
    potassium: 310,
    cholesterol: 55,
    vitaminA: 40,
    vitaminC: 4.5,
    calcium: 80,
    iron: 2.2,
    brand: "McDonalds",
    country: "IN",
    aliases: ["mcspicy burger", "chicken mcspicy", "mcdonalds chicken burger"],
    popularityScore: 96,
    verificationStatus: "Verified"
  },
  {
    id: "rest-mcd-fries",
    name: "McDonald's Salted French Fries (Medium)",
    servingSize: "1 serving (117g)",
    calories: 340,
    protein: 4.0,
    carbs: 44.0,
    fat: 16.0,
    category: "Snacks",
    fiber: 4.0,
    sugar: 0.5,
    sodium: 260,
    potassium: 540,
    cholesterol: 0,
    vitaminA: 0,
    vitaminC: 4.8,
    calcium: 18,
    iron: 1.1,
    brand: "McDonalds",
    country: "Global",
    aliases: ["mcd fries", "french fries", "salted chips", "potatoes fry mcd"],
    popularityScore: 98,
    verificationStatus: "Verified"
  },
  {
    id: "rest-starbucks-latte",
    name: "Starbucks Iced Caffè Latte (Grande)",
    servingSize: "1 serving (473ml)",
    calories: 130,
    protein: 8.0,
    carbs: 13.0,
    fat: 4.5,
    category: "Other",
    fiber: 0,
    sugar: 11.0,
    sodium: 115,
    potassium: 380,
    cholesterol: 15,
    vitaminA: 150,
    vitaminC: 0,
    calcium: 300,
    iron: 0.1,
    brand: "Starbucks",
    barcode: "8801043014847",
    country: "Global",
    aliases: ["starbucks latte", "iced latte grande", "latte coffee", "caffe latte"],
    popularityScore: 96,
    verificationStatus: "Verified"
  },
  {
    id: "rest-saravana-idli",
    name: "Saravana Bhavan Mini Ghee Sambar Idli",
    servingSize: "1 bowl (14 pieces + Sambar)",
    calories: 320,
    protein: 8.5,
    carbs: 48,
    fat: 9.8,
    category: "Breakfast",
    fiber: 5.2,
    sugar: 4.1,
    sodium: 680,
    potassium: 240,
    cholesterol: 15,
    vitaminA: 65,
    vitaminC: 4.0,
    calcium: 78,
    iron: 2.1,
    brand: "Saravana Bhavan",
    country: "IN",
    aliases: ["mini idli", "sambar idli ghee", "saravana bhavan breakfast"],
    popularityScore: 91,
    verificationStatus: "Verified"
  },
  {
    id: "rest-dominos-pep",
    name: "Domino's Pepperoni Pizza (Medium Slice)",
    servingSize: "1 slice (100g)",
    calories: 270,
    protein: 11.5,
    carbs: 26.0,
    fat: 13.0,
    category: "Lunch/Dinner",
    fiber: 1.5,
    sugar: 2.2,
    sodium: 640,
    potassium: 170,
    cholesterol: 32,
    vitaminA: 80,
    vitaminC: 1.8,
    calcium: 160,
    iron: 1.8,
    brand: "Domino's",
    country: "Global",
    aliases: ["dominos pizza slice", "pepperoni pizza slice", "dominos pepperoni"],
    popularityScore: 95,
    verificationStatus: "Verified"
  },
  // Required Indian Sweets & Snacks
  {
    id: "in-jalebi",
    name: "Jalebi",
    servingSize: "2 pieces (75g)",
    calories: 300,
    protein: 2.2,
    carbs: 58.0,
    fat: 7.0,
    category: "Snacks",
    fiber: 0.5,
    sugar: 44.0,
    sodium: 150,
    potassium: 40,
    country: "IN",
    aliases: ["jalebee", "jilipi", "indian sweet funnel cake"],
    popularityScore: 90,
    verificationStatus: "Verified"
  },
  {
    id: "in-gulab-jamun",
    name: "Gulab Jamun",
    servingSize: "2 pieces (80g)",
    calories: 320,
    protein: 4.8,
    carbs: 52.0,
    fat: 11.2,
    category: "Snacks",
    fiber: 0.2,
    sugar: 40.0,
    sodium: 120,
    potassium: 85,
    country: "IN",
    aliases: ["gulabjamun", "sweet milk dumplings"],
    popularityScore: 92,
    verificationStatus: "Verified"
  },
  {
    id: "in-rasgulla",
    name: "Rasgulla",
    servingSize: "2 pieces (100g)",
    calories: 250,
    protein: 4.0,
    carbs: 48.0,
    fat: 4.5,
    category: "Snacks",
    fiber: 0,
    sugar: 42.0,
    sodium: 90,
    potassium: 70,
    country: "IN",
    aliases: ["roshogolla", "rasgola", "sweet cheese balls"],
    popularityScore: 89,
    verificationStatus: "Verified"
  },
  {
    id: "in-kachori",
    name: "Pyaaz Kachori",
    servingSize: "1 large piece (85g)",
    calories: 290,
    protein: 5.5,
    carbs: 34.0,
    fat: 14.5,
    category: "Snacks",
    fiber: 2.5,
    sugar: 1.5,
    sodium: 410,
    potassium: 160,
    country: "IN",
    aliases: ["khasta kachori", "onion kachori", "kachodi"],
    popularityScore: 85,
    verificationStatus: "Verified"
  },
  {
    id: "in-naan",
    name: "Butter Naan",
    servingSize: "1 piece (90g)",
    calories: 310,
    protein: 8.5,
    carbs: 48.0,
    fat: 9.5,
    category: "Breads",
    fiber: 2.2,
    sugar: 2.0,
    sodium: 520,
    potassium: 140,
    country: "IN",
    aliases: ["plain naan", "garlic naan", "tandoori naan"],
    popularityScore: 94,
    verificationStatus: "Verified"
  },
  {
    id: "in-thepla",
    name: "Methi Thepla",
    servingSize: "2 pieces (60g)",
    calories: 210,
    protein: 5.5,
    carbs: 32.0,
    fat: 6.8,
    category: "Breads",
    fiber: 3.2,
    sugar: 1.1,
    sodium: 340,
    potassium: 155,
    country: "IN",
    aliases: ["gujarati thepla", "fenugreek flatbread"],
    popularityScore: 86,
    verificationStatus: "Verified"
  },
  {
    id: "in-misal-pav",
    name: "Misal Pav Combo",
    servingSize: "1 plate (2 Pav + Misal)",
    calories: 440,
    protein: 12.8,
    carbs: 64.0,
    fat: 15.5,
    category: "Lunch/Dinner",
    fiber: 6.5,
    sugar: 3.5,
    sodium: 890,
    potassium: 320,
    country: "IN",
    aliases: ["misalpav", "spicy sprouts curry with bread"],
    popularityScore: 88,
    verificationStatus: "Verified"
  },
  // Global Foods
  {
    id: "gl-pizza",
    name: "Cheese Pizza (Classic Slice)",
    servingSize: "1 slice (100g)",
    calories: 266,
    protein: 11.3,
    carbs: 30.0,
    fat: 10.1,
    category: "Lunch/Dinner",
    fiber: 1.5,
    sugar: 2.5,
    sodium: 556,
    potassium: 137,
    country: "Global",
    aliases: ["pizza slice", "margarita pizza", "margherita"],
    popularityScore: 98,
    verificationStatus: "Verified"
  },
  {
    id: "gl-burger",
    name: "Beef/Veggie Burger with Cheese",
    servingSize: "1 burger (150g)",
    calories: 390,
    protein: 19.5,
    carbs: 38.0,
    fat: 17.5,
    category: "Lunch/Dinner",
    fiber: 2.5,
    sugar: 6.0,
    sodium: 710,
    potassium: 290,
    country: "Global",
    aliases: ["hamburger", "cheeseburger", "cheese burger"],
    popularityScore: 97,
    verificationStatus: "Verified"
  },
  {
    id: "gl-pasta",
    name: "Penne Pasta in Arrabbiata Red Sauce",
    servingSize: "1 bowl (200g)",
    calories: 280,
    protein: 8.5,
    carbs: 52.0,
    fat: 4.8,
    category: "Lunch/Dinner",
    fiber: 3.8,
    sugar: 3.5,
    sodium: 480,
    potassium: 190,
    country: "Global",
    aliases: ["pasta arrabbiata", "red sauce pasta", "cooked pasta"],
    popularityScore: 93,
    verificationStatus: "Verified"
  },
  {
    id: "gl-sandwich",
    name: "Grilled Chicken/Veg Sandwich",
    servingSize: "1 sandwich (140g)",
    calories: 320,
    protein: 14.5,
    carbs: 36.0,
    fat: 12.2,
    category: "Lunch/Dinner",
    fiber: 3.0,
    sugar: 4.0,
    sodium: 680,
    potassium: 210,
    country: "Global",
    aliases: ["club sandwich", "toast sandwich", "grilled sandwich"],
    popularityScore: 95,
    verificationStatus: "Verified"
  },
  {
    id: "gl-salad",
    name: "Greek Salad / Garden Green Salad",
    servingSize: "1 bowl (150g)",
    calories: 120,
    protein: 2.5,
    carbs: 8.0,
    fat: 9.2,
    category: "Lunch/Dinner",
    fiber: 2.8,
    sugar: 3.5,
    sodium: 380,
    potassium: 240,
    country: "Global",
    aliases: ["green salad", "caesar salad", "healthy salad"],
    popularityScore: 92,
    verificationStatus: "Verified"
  },
  {
    id: "gl-sushi",
    name: "Sushi Maki Rolls (Salmon/Avocado)",
    servingSize: "6 pieces (150g)",
    calories: 220,
    protein: 9.0,
    carbs: 38.0,
    fat: 3.5,
    category: "Lunch/Dinner",
    fiber: 1.5,
    sugar: 2.0,
    sodium: 450,
    potassium: 190,
    country: "Global",
    aliases: ["sushi roll", "maki sushi", "california roll"],
    popularityScore: 88,
    verificationStatus: "Verified"
  },
  {
    id: "gl-steak",
    name: "Grilled Tenderloin Steak",
    servingSize: "1 steak serving (200g)",
    calories: 380,
    protein: 42.0,
    carbs: 0.5,
    fat: 22.0,
    category: "Lunch/Dinner",
    fiber: 0,
    sugar: 0,
    sodium: 580,
    potassium: 490,
    country: "Global",
    aliases: ["beef steak", "meat steak", "grilled steak"],
    popularityScore: 86,
    verificationStatus: "Verified"
  },
  {
    id: "gl-fried-rice",
    name: "Chinese Veg/Egg Fried Rice",
    servingSize: "1 bowl (200g)",
    calories: 340,
    protein: 7.5,
    carbs: 62.0,
    fat: 6.8,
    category: "Lunch/Dinner",
    fiber: 2.2,
    sugar: 1.5,
    sodium: 590,
    potassium: 160,
    country: "Global",
    aliases: ["fried rice", "chinese rice", "egg fried rice"],
    popularityScore: 95,
    verificationStatus: "Verified"
  },
  {
    id: "gl-noodles",
    name: "Hakka Noodles (Chinese Style)",
    servingSize: "1 bowl (200g)",
    calories: 310,
    protein: 6.8,
    carbs: 58.0,
    fat: 5.5,
    category: "Lunch/Dinner",
    fiber: 2.5,
    sugar: 2.0,
    sodium: 610,
    potassium: 145,
    country: "Global",
    aliases: ["chow mein", "hakka noodles", "chinese noodles"],
    popularityScore: 94,
    verificationStatus: "Verified"
  },
  {
    id: "gl-tofu",
    name: "Organic Firm Tofu",
    servingSize: "100g",
    calories: 80,
    protein: 8.0,
    carbs: 2.0,
    fat: 5.0,
    category: "Other",
    fiber: 1.0,
    sodium: 12,
    country: "Global",
    aliases: ["tofu", "soya paneer", "soy curd", "bean curd"],
    popularityScore: 90,
    verificationStatus: "Verified"
  },
  {
    id: "gl-oats",
    name: "Rolled Oats",
    servingSize: "1 bowl (40g)",
    calories: 150,
    protein: 5.0,
    carbs: 27.0,
    fat: 3.0,
    category: "Breakfast",
    fiber: 4.0,
    sodium: 2,
    country: "Global",
    aliases: ["oats", "oatmeal", "rolled oats", "porridge oats"],
    popularityScore: 95,
    verificationStatus: "Verified"
  }
];
